language: go

env:
  global:
    - GO111MODULE=on
#  - GOPROXY=https://proxy.golang.org

go:
  - "1.13"

before_script:
  - go get golang.org/x/lint/golint

script:
  - ./.ci/check.sh

cache:
  directories:
    - $HOME/gopath/pkg/mod
