sudo: required

env:
  global:
    - GO111MODULE=on

services:
  - docker

stages:
  - test
  - versioning
  - release
  - chart

jobs:
  include:
    - stage: test
      language: go
      go: "1.13"
      script:
        - go get golang.org/x/lint/golint
        - ./.ci/check.sh
    - stage: versioning
      language: node_js
      node_js: "10"
      install:
        - npm install -g semantic-release @semantic-release/release-notes-generator @semantic-release/commit-analyzer @semantic-release/changelog @semantic-release/github @semantic-release/git
      if: branch = master
      script:
        - semantic-release
    - stage: release
      language: go
      go: "1.13"
      addons:
        apt:
          packages:
            - snapd
      env:
        - PATH=/snap/bin:$PATH
      install:
        - sudo snap install snapcraft --classic
      if: branch = master
      deploy:
        - provider: script
          skip_cleanup: true
          overwrite: true
          script:
            git pull && curl -sL https://git.io/goreleaser | bash
    - stage: chart
      language: minimal
      if: branch = master
      env:
        - NAME=uropa
        - TEAM=ninjaneers-team
        - REPOSITORY=helm
      before_install:
        - curl -L https://git.io/get_helm.sh | bash
        - helm init --client-only
      script:
        - helm lint
        - helm package charts/$NAME --version=$TRAVIS_TAG
        - ./.ci/update_chart.sh
cache:
  directories:
    - $HOME/gopath/pkg/mod